name: GERP Synchronize Templates

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  sync-templates:
    name: Sync Templates
    uses: gerp-project/gerp/.github/workflows/sync_templates.yaml@v0
    secrets:
      PAT: ${{ secrets.PAT }}
