name: Template dispatch

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
   release-pr:
      uses: gerp-project/gerp/.github/workflows/template_dispatch.yaml@main
      secrets:
        PAT: ${{ secrets.PAT }}
